package vn.com.vhc.consolidate.models;

public class Report {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_3G_TT_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll3gTtDatacard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_3G_TT_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll3gTtMaydt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_3G_TS_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll3gTsDatacard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_3G_TS_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll3gTsMaydt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_2G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll2gTt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.PSLL_2G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer psll2gTs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBKH_2G_3G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbkh2g3gTt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBKH_2G_3G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbkh2g3gTs;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_2G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd2gT1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_3G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd3gT1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_2G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd2gT2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_3G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd3gT2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_2G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd2gT3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_3G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd3gT3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_2G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd2gT4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column REPORT.TBHD_3G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	private Integer tbhd3gT4;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_3G_TT_DATACARD
	 *
	 * @return the value of REPORT.PSLL_3G_TT_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll3gTtDatacard() {
		return psll3gTtDatacard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_3G_TT_DATACARD
	 *
	 * @param psll3gTtDatacard
	 *            the value for REPORT.PSLL_3G_TT_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll3gTtDatacard(Integer psll3gTtDatacard) {
		this.psll3gTtDatacard = psll3gTtDatacard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_3G_TT_MAYDT
	 *
	 * @return the value of REPORT.PSLL_3G_TT_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll3gTtMaydt() {
		return psll3gTtMaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_3G_TT_MAYDT
	 *
	 * @param psll3gTtMaydt
	 *            the value for REPORT.PSLL_3G_TT_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll3gTtMaydt(Integer psll3gTtMaydt) {
		this.psll3gTtMaydt = psll3gTtMaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_3G_TS_DATACARD
	 *
	 * @return the value of REPORT.PSLL_3G_TS_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll3gTsDatacard() {
		return psll3gTsDatacard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_3G_TS_DATACARD
	 *
	 * @param psll3gTsDatacard
	 *            the value for REPORT.PSLL_3G_TS_DATACARD
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll3gTsDatacard(Integer psll3gTsDatacard) {
		this.psll3gTsDatacard = psll3gTsDatacard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_3G_TS_MAYDT
	 *
	 * @return the value of REPORT.PSLL_3G_TS_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll3gTsMaydt() {
		return psll3gTsMaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_3G_TS_MAYDT
	 *
	 * @param psll3gTsMaydt
	 *            the value for REPORT.PSLL_3G_TS_MAYDT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll3gTsMaydt(Integer psll3gTsMaydt) {
		this.psll3gTsMaydt = psll3gTsMaydt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_2G_TT
	 *
	 * @return the value of REPORT.PSLL_2G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll2gTt() {
		return psll2gTt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_2G_TT
	 *
	 * @param psll2gTt
	 *            the value for REPORT.PSLL_2G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll2gTt(Integer psll2gTt) {
		this.psll2gTt = psll2gTt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.PSLL_2G_TS
	 *
	 * @return the value of REPORT.PSLL_2G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getPsll2gTs() {
		return psll2gTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.PSLL_2G_TS
	 *
	 * @param psll2gTs
	 *            the value for REPORT.PSLL_2G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setPsll2gTs(Integer psll2gTs) {
		this.psll2gTs = psll2gTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBKH_2G_3G_TT
	 *
	 * @return the value of REPORT.TBKH_2G_3G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbkh2g3gTt() {
		return tbkh2g3gTt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBKH_2G_3G_TT
	 *
	 * @param tbkh2g3gTt
	 *            the value for REPORT.TBKH_2G_3G_TT
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbkh2g3gTt(Integer tbkh2g3gTt) {
		this.tbkh2g3gTt = tbkh2g3gTt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBKH_2G_3G_TS
	 *
	 * @return the value of REPORT.TBKH_2G_3G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbkh2g3gTs() {
		return tbkh2g3gTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBKH_2G_3G_TS
	 *
	 * @param tbkh2g3gTs
	 *            the value for REPORT.TBKH_2G_3G_TS
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbkh2g3gTs(Integer tbkh2g3gTs) {
		this.tbkh2g3gTs = tbkh2g3gTs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_2G_T1
	 *
	 * @return the value of REPORT.TBHD_2G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd2gT1() {
		return tbhd2gT1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_2G_T1
	 *
	 * @param tbhd2gT1
	 *            the value for REPORT.TBHD_2G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd2gT1(Integer tbhd2gT1) {
		this.tbhd2gT1 = tbhd2gT1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_3G_T1
	 *
	 * @return the value of REPORT.TBHD_3G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd3gT1() {
		return tbhd3gT1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_3G_T1
	 *
	 * @param tbhd3gT1
	 *            the value for REPORT.TBHD_3G_T1
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd3gT1(Integer tbhd3gT1) {
		this.tbhd3gT1 = tbhd3gT1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_2G_T2
	 *
	 * @return the value of REPORT.TBHD_2G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd2gT2() {
		return tbhd2gT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_2G_T2
	 *
	 * @param tbhd2gT2
	 *            the value for REPORT.TBHD_2G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd2gT2(Integer tbhd2gT2) {
		this.tbhd2gT2 = tbhd2gT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_3G_T2
	 *
	 * @return the value of REPORT.TBHD_3G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd3gT2() {
		return tbhd3gT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_3G_T2
	 *
	 * @param tbhd3gT2
	 *            the value for REPORT.TBHD_3G_T2
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd3gT2(Integer tbhd3gT2) {
		this.tbhd3gT2 = tbhd3gT2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_2G_T3
	 *
	 * @return the value of REPORT.TBHD_2G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd2gT3() {
		return tbhd2gT3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_2G_T3
	 *
	 * @param tbhd2gT3
	 *            the value for REPORT.TBHD_2G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd2gT3(Integer tbhd2gT3) {
		this.tbhd2gT3 = tbhd2gT3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_3G_T3
	 *
	 * @return the value of REPORT.TBHD_3G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd3gT3() {
		return tbhd3gT3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_3G_T3
	 *
	 * @param tbhd3gT3
	 *            the value for REPORT.TBHD_3G_T3
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd3gT3(Integer tbhd3gT3) {
		this.tbhd3gT3 = tbhd3gT3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_2G_T4
	 *
	 * @return the value of REPORT.TBHD_2G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd2gT4() {
		return tbhd2gT4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_2G_T4
	 *
	 * @param tbhd2gT4
	 *            the value for REPORT.TBHD_2G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd2gT4(Integer tbhd2gT4) {
		this.tbhd2gT4 = tbhd2gT4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column REPORT.TBHD_3G_T4
	 *
	 * @return the value of REPORT.TBHD_3G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public Integer getTbhd3gT4() {
		return tbhd3gT4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column REPORT.TBHD_3G_T4
	 *
	 * @param tbhd3gT4
	 *            the value for REPORT.TBHD_3G_T4
	 *
	 * @mbggenerated Thu Sep 06 09:05:32 ICT 2018
	 */
	public void setTbhd3gT4(Integer tbhd3gT4) {
		this.tbhd3gT4 = tbhd3gT4;
	}

	private Integer ttTong3G;
	
	private Integer tsTong3G;
	
	private Integer tong3G;
	
	private Integer tong2G;
	
	private Integer psllTong2G3G;
	
	private Integer tong2G3G;
	
	private Integer tong2G3Gtuan1;
	
	private Integer tong2G3Gtuan2;
	
	private Integer tong2G3Gtuan3;
	
	private Integer tong2G3Gtuan4;

	public Integer getTtTong3G() {
		return ttTong3G;
	}

	public void setTtTong3G(Integer ttTong3G) {
		this.ttTong3G = ttTong3G;
	}

	public Integer getTsTong3G() {
		return tsTong3G;
	}

	public void setTsTong3G(Integer tsTong3G) {
		this.tsTong3G = tsTong3G;
	}

	public Integer getTong3G() {
		return tong3G;
	}

	public void setTong3G(Integer tong3g) {
		tong3G = tong3g;
	}

	public Integer getTong2G() {
		return tong2G;
	}

	public void setTong2G(Integer tong2g) {
		tong2G = tong2g;
	}

	public Integer getPsllTong2G3G() {
		return psllTong2G3G;
	}

	public void setPsllTong2G3G(Integer psllTong2G3G) {
		this.psllTong2G3G = psllTong2G3G;
	}

	public Integer getTong2G3G() {
		return tong2G3G;
	}

	public void setTong2G3G(Integer tong2g3g) {
		tong2G3G = tong2g3g;
	}

	public Integer getTong2G3Gtuan1() {
		return tong2G3Gtuan1;
	}

	public void setTong2G3Gtuan1(Integer tong2g3Gtuan1) {
		tong2G3Gtuan1 = tong2g3Gtuan1;
	}

	public Integer getTong2G3Gtuan2() {
		return tong2G3Gtuan2;
	}

	public void setTong2G3Gtuan2(Integer tong2g3Gtuan2) {
		tong2G3Gtuan2 = tong2g3Gtuan2;
	}

	public Integer getTong2G3Gtuan3() {
		return tong2G3Gtuan3;
	}

	public void setTong2G3Gtuan3(Integer tong2g3Gtuan3) {
		tong2G3Gtuan3 = tong2g3Gtuan3;
	}

	public Integer getTong2G3Gtuan4() {
		return tong2G3Gtuan4;
	}

	public void setTong2G3Gtuan4(Integer tong2g3Gtuan4) {
		tong2G3Gtuan4 = tong2g3Gtuan4;
	}
	
}
